export const LIST_STATUS_ORDERED = [
  'dp',
  'stand by',
  'stand_by',
  'standby',
  'stand by ready',
  'stand_by_ready',
  'standbyready',
  'underway using engine',
  'underway_using_engine',
  'underway',
  'under way',
  'under way using engine',
  'under_way_using_engine',
  'fast transit',
  'fasttransit',
  'fast_transit',
  'transit',
  'slow',
  'at anchor',
  'at_anchor',
  'moored',
  'port',
  'dock',
  'stopped',
  'other',
];
