export const SET_ENTERPRISES_FILTER = "SET_ENTERPRISES_FILTER";
export const SET_VISIBLE_ENTERPRISES_FILTER = "SET_VISIBLE_ENTERPRISES_FILTER";

export const SET_THEME_SETTINGS = "SET_THEME_SETTINGS";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_TOGGLE_MENU = "SET_TOGGLE_MENU";

export const SET_ITEMS_MENU = "SET_ITEMS_MENU";
export const SET_STATE_VISIBLE_MENU = "SET_STATE_VISIBLE_MENU";
export const SET_STATE_VIEWER_DRAG_MENU = "SET_STATE_VIEWER_DRAG_MENU";
export const SET_MENU_STATE = "SET_MENU_STATE";

export const SET_DISABLED_BTN_SAVE = "SET_DISABLED_BTN_SAVE";
export const SET_DATA_CHART = "SET_DATA_CHART";
export const ADD_NEW_CHART = "ADD_NEW_CHART";
export const SET_FILTER_DASHBOARD = "SET_FILTER_DASHBOARD";
export const SET_EDITOR_ITEM = "SET_EDITOR_ITEM";
export const SET_DRAG_ENABLED = "SET_DRAG_ENABLED";
export const SET_LIST_GROUP = "SET_LIST_GROUP";
export const ADD_GROUP = "ADD_GROUP";

export const SET_NEW_NOTIFICATIONS = "SET_NEW_NOTIFICATIONS";

export const SET_LAST_SENSOR_STATE = "SET_LAST_SENSOR_STATE";
export const SET_ISLOADING_LAST_SENSOR_STATE =
  "SET_ISLOADING_LAST_SENSOR_STATE";

export const SET_ISLOADING_MACHINE_POINTS = "SET_ISLOADING_MACHINE_POINTS";
export const SET_MACHINE_DETAILS_POINTS = "SET_MACHINE_DETAILS_POINTS";
export const SET_POSITIONS = "SET_POSITIONS";
export const SET_COURSES = "SET_COURSES";
export const SET_ISLOADING_STATUS_MACHINE = "SET_ISLOADING_STATUS_MACHINE";
export const SET_STATUS_MACHINE = "SET_STATUS_MACHINE";
export const SET_MACHINE_FILTER = "SET_MACHINE_FILTER";
export const SET_IS_SHOW_LIST_FLEET = "SET_IS_SHOW_LIST_FLEET";
export const SET_TRAVEL_SELECTED = "SET_TRAVEL_SELECTED";
export const SET_LAST_MARKER = "SET_LAST_MARKER";
export const SET_ITEM_POINT_DETAILS = "SET_ITEM_POINT_DETAILS";
export const SET_ROUTE_HISTORY = "SET_ROUTE_HISTORY";
export const SET_MACHINES = "SET_MACHINES";
export const SET_MACHINE_CONSUME_DETAILS = "SET_MACHINE_CONSUME_DETAILS";
export const SET_ITEM_HISTORY_CONSUME = "SET_ITEM_HISTORY_CONSUME";
export const SET_EVENTS_STATUS_CONSUME = "SET_EVENTS_STATUS_CONSUME";
export const SET_ROUTE_CONSUMPTION = "SET_ROUTE_CONSUMPTION";
export const SET_ROUTE_CONSUMPTION_SENSORS = "SET_ROUTE_CONSUMPTION_SENSORS";
export const SET_MACHINE_CREW_SELECTED = "SET_MACHINE_CREW_SELECTED";
export const SET_ROUTE_BACK_SELECTED = "SET_ROUTE_BACK_SELECTED";
export const SET_MACHINE_INFO_SELECTED = "SET_MACHINE_INFO_SELECTED";
export const SET_MACHINE_CONTACT_SELECTED = "SET_MACHINE_CONTACT_SELECTED";
export const SET_MACHINE_CAMERAS_SELECTED = "SET_MACHINE_CAMERAS_SELECTED";
export const SET_ASSET_VOYAGE_SELECTED = "SET_ASSET_VOYAGE_SELECTED";
export const SET_EVENT_TIMELINE_SELECT = "SET_EVENT_TIMELINE_SELECT";
export const RESET_STATE_FLEET = "RESET_STATE_FLEET";
export const SET_ROUTE_INTEGRATION = "SET_ROUTE_INTEGRATION";
export const SET_SHOW_AIS = "SET_SHOW_AIS";
export const SET_PORT_FILTER_ACTIVITY = "SET_PORT_FILTER_ACTIVITY";

export const SET_MAP_SHOW_CODE = "SET_MAP_SHOW_CODE";
export const SET_MAP_SHOW_NAME = "SET_MAP_SHOW_NAME";
export const SET_MAP_SHOW_NAME_FENCE = "SET_MAP_SHOW_NAME_FENCE";
export const SET_MAP_TECH = "SET_MAP_TECH";
export const SET_MAP_ROUTER = "SET_MAP_ROUTER";
export const SET_ROUTER_IS_LOADING = "SET_ROUTER_IS_LOADING";
export const SET_MAP_THEME = "SET_MAP_THEME";
export const SET_FILTER_ROUTER = "SET_FILTER_ROUTER";
export const SET_IS_SHOW_POINTS = "SET_IS_SHOW_POINTS";
export const SET_IS_SHOW_SEQUENCE_POINTS = "SET_IS_SHOW_SEQUENCE_POINTS";
export const SET_IS_SHOW_PREDICTION_ROUTE = "SET_IS_SHOW_PREDICTION_ROUTE";
export const SET_TIME_PLAYBACK = "SET_TIME_PLAYBACK";
export const SET_PLAY_PAUSE_PLAYBACK = "SET_PLAY_PAUSE_PLAYBACK";
export const SET_SPEED_PLAYBACK = "SET_SPEED_PLAYBACK";
export const SET_IS_REGION_PLAYBACK = "SET_IS_REGION_PLAYBACK";
export const SET_STOP_PLAYBACK = "SET_STOP_PLAYBACK";
export const SET_IS_COLOR_STATUS_FLEET = "SET_IS_COLOR_STATUS_FLEET";
export const SET_IS_NAVIGATION = "SET_IS_NAVIGATION";
export const SET_IS_OPERATION = "SET_IS_OPERATION";

export const SET_DATA_VOYAGE = "SET_DATA_VOYAGE";
export const ADD_DATA_VOYAGE = "ADD_DATA_VOYAGE";
export const ADD_DATA_CONSUME_VOYAGE = "ADD_DATA_CONSUME_VOYAGE";
export const SET_INTEGRATION_VOYAGE_SELECTED =
  "SET_INTEGRATION_VOYAGE_SELECTED";
export const SET_VOYAGE_KICK_FILTER = "SET_VOYAGE_KICK_FILTER";
export const SET_INTEGRATION_ASSETS_SELECTED =
  "SET_INTEGRATION_ASSETS_SELECTED";

export const SET_USERS_FILTER = "SET_USERS_FILTER";
export const SET_USER_FILTER_WHATSAPP = "SET_USER_FILTER_WHATSAPP";

export const SET_FIELDS_FORM = "SET_FIELDS_FORM";
export const ADD_FIELDS_FORM = "ADD_FIELDS_FORM";
export const SET_FORM = "SET_FORM";

export const SET_DATA_STATUS_CONSUME = "SET_DATA_STATUS_CONSUME";
export const SET_ISLOADING_STATUS_CONSUME = "SET_ISLOADING_STATUS_CONSUME";
export const SET_FILTER_STATUS_CONSUME = "SET_FILTER_STATUS_CONSUME";
export const SET_UNIT_STATUS_CONSUME = "SET_UNIT_STATUS_CONSUME";

export const SET_LAST_FILLED_FORM_BOARD = "SET_LAST_FILLED_FORM_BOARD";

export const SET_FILTER_IHM = "SET_FILTER_IHM";
export const SET_IS_EDITING_IHM = "SET_IS_EDITING_IHM";
export const SET_IHM_DATA = "SET_IHM_DATA";
export const SET_IHM_PMS_DATA = "SET_IHM_PMS_DATA";
export const SET_IS_LOADING_IHM = "SET_IS_LOADING_IHM";
export const SET_IHM_SENSOR_LIST = "SET_IHM_SENSOR_LIST";
export const ADD_EMPTY_GENERATOR = "ADD_EMPTY_GENERATOR";
export const ADD_EMPTY_THRUSTER = "ADD_EMPTY_THRUSTER";
export const SET_FIRST_FETCH_FLAG = " SET_FIRST_FETCH_FLAG";

export const SET_OPERATION_MACHINES = "SET_OPERATION_MACHINES";

export const SET_IS_SHOW_WEATHER_ROUTE = "SET_IS_SHOW_WEATHER_ROUTE";
export const SET_IS_SHOW_DIRECTION_ROUTE = "SET_IS_SHOW_DIRECTION_ROUTE";
export const SET_IS_SHOW_ROUTE = "SET_IS_SHOW_ROUTE";

export const SET_IS_SHOW_MESAURE_LINE= "SET_IS_SHOW_MESAURE_LINE";
export const SET_POINTS_MEASURE_LINE = "SET_POINTS_MEASURE_LINE";
export const SET_UNIT_MEASURE_LINE = "SET_UNIT_MEASURE_LINE";

export const SET_FORCE_UPDATE = "SET_FORCE_UPDATE";
