import {
  getStatusConsume,
  setDataStatusConsume,
  setFilterStatusConsume,
  setUnitStatusConsume,
} from "./chartData.action";
import {
  addGroup,
  addNewChart,
  setDataChart,
  setDisabledSave,
  setDragEnabled,
  setEditorItem,
  setFilterDashboard,
  setListGroup,
} from "./dashboard.action";
import {
  setEnteprisesFilter,
  setVisibleEnteprisesFilter,
} from "./enterpriseFilter.action";
import {
  clearPoints,
  getPointsDetailsFleet,
  getRouteIntegration,
  getStatusMachines,
  resetStateFleet,
  setCourses,
  setEventsStatusConsume,
  setIsShowList,
  setItemHistoryConsume,
  setLastMarker,
  setListSelectedPoint,
  setMachineCamerasSelected,
  setMachineConsume,
  setMachineContactSelected,
  setMachineCrew,
  setMachineDetailsSelected,
  setMachineInfoSelected,
  setMachines,
  setPositions,
  setRouteBack,
  setRouteConsumptionData,
  setRouteHistory,
  setRouteIntegration,
  setTimelineSelected,
  setTravelDetailsSelected,
  setAssetVoyageSelected
} from "./fleet.action";
import { addFormFields, setForm, setFormFields } from "./form.action.types";
import { setLastFilledForm } from "./formBoard.action";
import {
  setFilterMapRouter,
  setFilterPortActivity,
  setIsColorStatusFleet,
  setIsRegionPlayback,
  setIsShowPoints,
  setIsShowPreditionRoute,
  setIsShowSequencePoints,
  setMapRouter,
  setMapTech,
  setMapTheme,
  setOperationMachines,
  setPausePlayback,
  setRouterIsLoading,
  setShowAISVessels,
  setShowCode,
  setShowName,
  setShowNameFence,
  setSpeedPlayback,
  setStartPlayback,
  setStopPlayback,
  setTimePlayback,
  setIsShowMeasureLine,
  setUnitMeasureLine,
  setPointsMeasureLine,
} from "./map.actions";
import {
  getItemsMenu,
  resetItensMenu,
  setStateViewer,
  setVisible,
  setMenuState,
  setMenuFixed,
} from "./menu.action";
import { setNewNotifications } from "./notification.action";
import { getLastStatesSensorByMachines } from "./sensorState.action";
import { setLanguage, setTheme, setToggleMenu } from "./settings.actions";
import { setUserFilterWhatsapp, setUsersFilter } from "./statistics.action";
import {
  addDataConsumeVoyage,
  addDataVoyage,
  setAssetIntegrationVoyageSelect,
  setDataVoyage,
  setIntegrationVoyage,
  setKickVoyageFilter,
} from "./voyage.actions";

export {
  addDataConsumeVoyage,
  addDataVoyage,
  addFormFields,
  addGroup,
  addNewChart,
  clearPoints,
  getItemsMenu,
  setMenuState,
  getLastStatesSensorByMachines,
  getPointsDetailsFleet,
  getRouteIntegration,
  getStatusConsume,
  getStatusMachines,
  resetItensMenu,
  resetStateFleet,
  setAssetIntegrationVoyageSelect,
  setCourses,
  setDataChart,
  setDataStatusConsume,
  setDataVoyage,
  setDisabledSave,
  setDragEnabled,
  setEditorItem,
  setEnteprisesFilter,
  setEventsStatusConsume,
  setFilterDashboard,
  setFilterMapRouter,
  setFilterPortActivity,
  setFilterStatusConsume,
  setForm,
  setFormFields,
  setIntegrationVoyage,
  setIsColorStatusFleet,
  setIsRegionPlayback,
  setIsShowList,
  setIsShowPoints,
  setIsShowPreditionRoute,
  setIsShowSequencePoints,
  setItemHistoryConsume,
  setKickVoyageFilter,
  setLanguage,
  setLastFilledForm,
  setLastMarker,
  setListGroup,
  setListSelectedPoint,
  setMachineCamerasSelected,
  setMachineConsume,
  setMachineContactSelected,
  setMachineCrew,
  setMachineDetailsSelected,
  setMachineInfoSelected,
  setMachines,
  setMapRouter,
  setMapTech,
  setMapTheme,
  setNewNotifications,
  setOperationMachines,
  setPausePlayback,
  setPositions,
  setRouteBack,
  setRouteConsumptionData,
  setRouteHistory,
  setRouteIntegration,
  setRouterIsLoading,
  setShowAISVessels,
  setShowCode,
  setShowName,
  setShowNameFence,
  setSpeedPlayback,
  setStartPlayback,
  setStateViewer,
  setStopPlayback,
  setTheme,
  setTimelineSelected,
  setTimePlayback,
  setToggleMenu,
  setTravelDetailsSelected,
  setUnitStatusConsume,
  setUserFilterWhatsapp,
  setUsersFilter,
  setVisible,
  setVisibleEnteprisesFilter,
  setIsShowMeasureLine,
  setPointsMeasureLine,
  setUnitMeasureLine,
  setAssetVoyageSelected
};
