import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  BarChart3,
  Bell,
  Building2,
  CalendarClock,
  CheckSquare,
  FileText,
  Flame,
  Fuel,
  KeySquare,
  LayoutDashboard,
  Leaf,
  Mail,
  MapIcon,
  MapPin,
  MessageSquare,
  MonitorCog,
  Network,
  NotebookPen,
  Settings,
  Shield,
  Ship,
  Timer,
  Users,
  Variable,
  Wrench,
} from 'lucide-react';

// Mapeamento de ícones por segmento de rota
export const ROUTE_ICONS: Record<string, LucideIcon> = {
  permissions: KeySquare,
  'set-up-company': MonitorCog,
  maintenance: Wrench,
  register: NotebookPen,
  'fleet-manager': MapIcon,
  esg: Leaf,
  statistics: BarChart3,
  consumo: Fuel,
};

// Ícones para sub-rotas específicas
export const SUB_ROUTE_ICONS: Record<string, LucideIcon> = {
  users: Users,
  roles: Shield,
  'setup-email': Mail,
  'setup-api-external': Network,
  'integration-list': Building2,
  'monitoring-plans': CalendarClock,
  'monitoring-wear': Activity,
  'list-os-done': CheckSquare,
  sensors: Activity,
  enterprises: Building2,
  alerts: Bell,
  contracts: FileText,
  'sensor-functions': Variable,
  'external-users': Users,
  'setup-chatbot': MessageSquare,
  'setup-fleet': MapPin,
  'setup-limits': Settings,
  'indicators-eeoi-cii': BarChart3,
  'cii-fleet': Ship,
  'simulator-cii': Activity,
  'consumption-co2': Flame,
  'tracking-activity': Activity,
  'time-operation': Timer,
  'rve-dashboard': LayoutDashboard,
  'kpis-cmms': BarChart3,
  integration: Network,
  daily: BarChart3,
  interval: Fuel,
  comparative: Activity,
  'rve-rdo': FileText,
  'rve-sounding': FileText,
};

// Chaves i18n para tradução de rotas
export const ROUTE_LABELS: Record<string, string> = {
  permissions: 'permissions',
  'set-up-company': 'setup.company',
  maintenance: 'maintenance',
  users: 'users',
  roles: 'role',
  'setup-email': 'setup.email',
  'setup-api-external': 'setup.api.external',
  'integration-list': 'integration',
  'monitoring-plans': 'monitoring.plan',
  'monitoring-wear': 'monitoring.wear.part',
  'list-os-done': 'done.os',
  alerts: 'alerts',
  contracts: 'contracts',
  'sensor-functions': 'sensor-functions',
  'external-users': 'usernames.external',
  'setup-chatbot': 'setup.chatbot',
  'setup-fleet': 'setup.fleet',
  'setup-limits': 'setup.limits',
  'fleet-manager': 'fleet.manager',
  esg: 'esg.upper',
  'indicators-eeoi-cii': 'menu.eeoi.cii',
  'cii-fleet': 'esg.fleet',
  'simulator-cii': 'simulator.cii',
  'consumption-co2': 'esg.co2',
  statistics: 'statistics',
  'tracking-activity': 'tracking.activity',
  'time-operation': 'time.operation',
  'rve-dashboard': 'RVE Dashboard',
  'kpis-cmms': "KPI's CMMS",
  integration: 'integration',
  consumo: 'consumption',
  daily: 'consumption.daily',
  interval: 'consumption.interval',
  comparative: 'consumption.comparative',
  'rve-rdo': 'consumption.rve.rdo',
  'rve-sounding': 'consumption.rve.sounding',
};

/**
 * Lista de rotas principais da aplicação.
 * Esta lista é derivada do FileRoutesByFullPath gerado pelo TanStack Router.
 *
 * NOTA: Mantenha sincronizado com as rotas disponíveis no projeto.
 * Novas rotas adicionadas ao projeto aparecerão em routeTree.gen.ts.
 */
export const MAIN_ROUTES = [
  '/consumo/comparative',
  '/consumo/daily',
  '/consumo/interval',
  '/consumo/rve-rdo',
  '/consumo/rve-sounding',
  '/consumo/time-operation',
  '/esg/cii-fleet',
  '/esg/consumption-co2',
  '/esg/indicators-eeoi-cii',
  '/esg/simulator-cii',
  '/fleet-manager',
  '/maintenance/list-os-done',
  '/maintenance/monitoring-plans',
  '/maintenance/monitoring-wear',
  '/permissions/roles',
  '/permissions/users',
  '/register/alerts',
  '/register/buoy',
  '/register/contracts',
  '/register/customers',
  '/register/enterprises',
  '/register/forms',
  '/register/geofences',
  '/register/machines',
  '/register/maintenance-plans',
  '/register/model-machine',
  '/register/params',
  '/register/parts',
  '/register/platform',
  '/register/sensor-functions',
  '/register/sensors',
  '/register/type-fuel',
  '/register/user-type',
  '/set-up-company/external-users',
  '/set-up-company/integration-list',
  '/set-up-company/setup-api-external',
  '/set-up-company/setup-chatbot',
  '/set-up-company/setup-email',
  '/set-up-company/setup-fleet',
  '/set-up-company/setup-limits',
  '/statistics/integration',
  '/statistics/kpis-cmms',
  '/statistics/rve-dashboard',
  '/statistics/time-operation',
  '/statistics/tracking-activity',
] as const;

export type MainRoute = (typeof MAIN_ROUTES)[number];
