import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  CalendarFold,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Contact,
  DollarSign,
  DoorOpen,
  FileText,
  Flame,
  Fuel,
  KeySquare,
  LayoutDashboard,
  Leaf,
  LifeBuoy,
  List,
  Mail,
  MapIcon,
  MapPin,
  MessageSquare,
  MonitorCog,
  Network,
  NotebookPen,
  Radio,
  Settings,
  Ship,
  Sparkles,
  Target,
  Timer,
  Users,
  Variable,
  Wrench,
  Zap,
} from 'lucide-react';

// Mapeamento de ícones por segmento de rota
export const ROUTE_ICONS: Record<string, LucideIcon> = {
  permissions: KeySquare,
  'set-up-company': MonitorCog,
  maintenance: Wrench,
  register: NotebookPen,
  'fleet-manager': MapIcon,
  esg: Leaf,
  statistics: BarChart3,
  consumption: Fuel,
  operation: Zap,
  ia: Sparkles,
  'calendar-maintenance': CalendarFold,
  telemetry: Radio,
  voyage: Ship,
  cmms: Wrench,
  'service-management': Briefcase,
  contracts: NotebookPen,
};

// Ícones para sub-rotas específicas
export const SUB_ROUTE_ICONS: Record<string, LucideIcon> = {
  users: Users,
  roles: DoorOpen,
  'setup-email': Mail,
  'setup-api-external': Network,
  'integration-list': Building2,
  'monitoring-plans': CalendarFold,
  'monitoring-wear': Activity,
  'list-os-done': CheckSquare,
  sensors: Activity,
  enterprises: Building2,
  alerts: Bell,
  contracts: FileText,
  'sensor-functions': Variable,
  'external-users': Users,
  'setup-chatbot': MessageSquare,
  'setup-fleet': MapPin,
  'setup-limits': Settings,
  'indicators-eeoi-cii': BarChart3,
  'cii-fleet': Ship,
  'simulator-cii': Activity,
  'consumption-co2': Flame,
  'tracking-activity': Activity,
  'time-operation': Timer,
  'rve-dashboard': LayoutDashboard,
  'kpis-cmms': BarChart3,
  integration: Network,
  daily: BarChart3,
  relatorio: Fuel,
  comparative: Activity,
  'rve-rdo': FileText,
  'rve-sounding': FileText,
  downtime: Clock,
  'operational-asset': Activity,
  'operational-fleet': LayoutDashboard,
  groups: Users,
  goals: Target,
  ptax: DollarSign,
  'anomaly-detector': Activity,
  prompt: Activity,
  datalogger: Activity,
  performance: BarChart3,
  'list-dashboard': LayoutDashboard,
  'remote-ihm': MonitorCog,
  'heatmap-fleet': MapPin,
  'heatmap-panel': BarChart3,
  'buoys-dwell-time': Timer,
  'download-data-asset-request': FileText,
  'diagram-list': Network,
  'filled-form-cmms': ClipboardCheck,
  'list-travel': List,
  'kpis-travel': BarChart3,
  'voyage-integration': Network,
  'route-planner': MapPin,
  fas: ClipboardList,
  'fas-analytics': BarChart3,
  'fas-contacts': Contact,
  'contract-list': List,
  buoy: LifeBuoy,
  customers: Users,
  forms: FileText,
  geofences: MapPin,
  machines: Ship,
  'maintenance-plans': CalendarFold,
  'model-machine': MonitorCog,
  params: Settings,
  parts: Wrench,
  platform: Building2,
  'type-fuel': Fuel,
  'user-type': Users,
  'dashboard-rve': LayoutDashboard,
  'dashboard-rve-rdo': LayoutDashboard,
  'dashboard-rve-sounding': LayoutDashboard,
};

// Chaves i18n para tradução de rotas
export const ROUTE_LABELS: Record<string, string> = {
  permissions: 'permissions',
  'set-up-company': 'setup.company',
  maintenance: 'maintenance',
  users: 'users',
  roles: 'role',
  'setup-email': 'setup.email',
  'setup-api-external': 'setup.api.external',
  'integration-list': 'integration',
  'monitoring-plans': 'maintenance.plan',
  'monitoring-wear': 'monitoring.wear.part',
  'list-os-done': 'done.os',
  alerts: 'alerts',
  contracts: 'contracts',
  'sensor-functions': 'sensor-functions',
  'external-users': 'usernames.external',
  'setup-chatbot': 'setup.chatbot',
  'setup-fleet': 'fleet.manager',
  'setup-limits': 'setup.limits',
  'fleet-manager': 'fleet.manager',
  esg: 'esg',
  'indicators-eeoi-cii': 'menu.eeoi.cii',
  'cii-fleet': 'esg.fleet',
  'simulator-cii': 'simulator.cii',
  'consumption-co2': 'esg.co2',
  statistics: 'statistics',
  'tracking-activity': 'tracking.activity',
  'time-operation': 'time.operation',
  'rve-dashboard': 'rve.dashboard',
  'kpis-cmms': 'kpis.cmms',
  integration: 'integration',
  consumption: 'consume',
  daily: 'consumption.daily',
  relatorio: 'reports',
  comparative: 'consumption.comparative',
  'rve-rdo': 'dashboard.rve.rdo',
  'rve-sounding': 'dashboard.rve.sounding',
  operation: 'operation',
  downtime: 'downtime',
  'operational-asset': 'operational.asset',
  'operational-fleet': 'operational.fleet',
  groups: 'groups',
  goals: 'goals',
  ptax: 'ptax',
  ia: 'IA',
  'fleet-panel': 'fleet.panel',
  'anomaly-detector': 'menu.nexai.anomaly.detector',
  prompt: 'ai.prompt',
  'calendar-maintenance': 'calendar.maintenance',
  telemetry: 'telemetry',
  datalogger: 'telemetry.datalogger',
  performance: 'performance',
  'list-dashboard': 'telemetry.list.dashboard',
  'remote-ihm': 'telemetry.remote.ihm',
  'heatmap-fleet': 'telemetry.heatmap.fleet',
  'heatmap-panel': 'telemetry.heatmap.panel',
  'buoys-dwell-time': 'telemetry.buoys.dwell.time',
  'download-data-asset-request': 'telemetry.download.data.asset.request',
  'diagram-list': 'telemetry.diagram.list',
  voyage: 'travel',
  'list-travel': 'voyage.list',
  'kpis-travel': 'voyage.kpis',
  'voyage-integration': 'voyage.integration',
  'route-planner': 'route.planner',
  cmms: 'cmms',
  'filled-form-cmms': 'filled-form-cmms',
  sensors: 'sensors',
  'service-management': 'service-management',
  fas: 'fas',
  'fas-analytics': 'fas.analytics',
  'fas-contacts': 'fas.contacts',
  'contract-list': 'contracts',
  buoy: 'monobuoys',
  customers: 'customers',
  enterprises: 'enterprises',
  forms: 'form',
  geofences: 'geofences',
  machines: 'assets',
  'maintenance-plans': 'maintenance.plans',
  'maintenance-plans-description': 'maintenance.plans.description',
  'model-machine': 'model.machine',
  params: 'parameters',
  parts: 'parts',
  platform: 'platforms',
  'type-fuel': 'types.fuel',
  'user-type': 'user.type',
  'dashboard-rve': 'rve.dashboard',
  'dashboard-rve-rdo': 'dashboard.rve.rdo',
  'dashboard-rve-sounding': 'dashboard.rve.sounding',
  'sensor-min-max': 'sensor.min.max',
};

/**
 * Lista de rotas principais da aplicação.
 * Esta lista é derivada do FileRoutesByFullPath gerado pelo TanStack Router.
 *
 * NOTA: Mantenha sincronizado com as rotas disponíveis no projeto.
 * Novas rotas adicionadas ao projeto aparecerão em routeTree.gen.ts.
 */
export const MAIN_ROUTES = [
  '/calendar-maintenance',
  '/cmms/diagram-list',
  '/cmms/filled-form-cmms',
  '/cmms/kpis-cmms',
  '/consumption/comparative',
  '/consumption/daily',
  '/consumption/relatorio',
  '/consumption/rve-rdo',
  '/consumption/rve-sounding',
  '/consumption/time-operation',
  '/contracts/contract-list',
  '/contracts/dashboard-rve',
  '/contracts/dashboard-rve-rdo',
  '/contracts/dashboard-rve-sounding',
  '/esg/cii-fleet',
  '/esg/consumption-co2',
  '/esg/indicators-eeoi-cii',
  '/esg/simulator-cii',
  '/fleet-manager',
  '/ia/anomaly-detector',
  '/ia/prompt',
  '/maintenance/list-os-done',
  '/maintenance/monitoring-plans',
  '/maintenance/monitoring-wear',
  '/operation/downtime',
  '/operation/goals',
  '/operation/groups',
  '/operation/operational-asset',
  '/operation/operational-fleet',
  '/operation/ptax',
  '/permissions/roles',
  '/permissions/users',
  '/register/alerts',
  '/register/buoy',
  '/register/contracts',
  '/register/customers',
  '/register/enterprises',
  '/register/forms',
  '/register/geofences',
  '/register/machines',
  '/register/maintenance-plans',
  '/register/model-machine',
  '/register/params',
  '/register/parts',
  '/register/platform',
  '/register/sensor-functions',
  '/register/sensors',
  '/register/type-fuel',
  '/register/user-type',
  '/service-management/fas',
  '/service-management/fas-analytics',
  '/service-management/fas-contacts',
  '/set-up-company/external-users',
  '/set-up-company/integration-list',
  '/set-up-company/setup-api-external',
  '/set-up-company/setup-chatbot',
  '/set-up-company/setup-email',
  '/set-up-company/setup-fleet',
  '/set-up-company/setup-limits',
  '/statistics/integration',
  '/statistics/kpis-cmms',
  '/statistics/rve-dashboard',
  '/statistics/time-operation',
  '/statistics/tracking-activity',
  '/telemetry/buoys-dwell-time',
  '/telemetry/datalogger',
  '/telemetry/diagram-list',
  '/telemetry/download-data-asset-request',
  '/telemetry/fleet-panel',
  '/telemetry/heatmap-fleet',
  '/telemetry/heatmap-panel',
  '/telemetry/list-dashboard',
  '/telemetry/performance',
  '/telemetry/remote-ihm',
  '/telemetry/sensor-min-max',
  '/voyage/kpis-travel',
  '/voyage/list-travel',
  '/voyage/route-planner',
  '/voyage/voyage-integration',
] as const;

export type MainRoute = (typeof MAIN_ROUTES)[number];
