/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as PrivateAccessUserIndexRouteImport } from './routes/_private/access-user/index';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as PublicAppAuthIndexRouteImport } from './routes/_public/app-auth/index';
import { Route as IndexRouteImport } from './routes/index';

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicAppAuthIndexRoute = PublicAppAuthIndexRouteImport.update({
  id: '/app-auth/',
  path: '/app-auth/',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateAccessUserIndexRoute = PrivateAccessUserIndexRouteImport.update({
  id: '/access-user/',
  path: '/access-user/',
  getParentRoute: () => PrivateRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/access-user': typeof PrivateAccessUserIndexRoute;
  '/app-auth': typeof PublicAppAuthIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/access-user': typeof PrivateAccessUserIndexRoute;
  '/app-auth': typeof PublicAppAuthIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_private': typeof PrivateRouteWithChildren;
  '/_public': typeof PublicRouteWithChildren;
  '/_private/access-user/': typeof PrivateAccessUserIndexRoute;
  '/_public/app-auth/': typeof PublicAppAuthIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/access-user' | '/app-auth';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/access-user' | '/app-auth';
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/access-user/'
    | '/_public/app-auth/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public/app-auth/': {
      id: '/_public/app-auth/';
      path: '/app-auth';
      fullPath: '/app-auth';
      preLoaderRoute: typeof PublicAppAuthIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/access-user/': {
      id: '/_private/access-user/';
      path: '/access-user';
      fullPath: '/access-user';
      preLoaderRoute: typeof PrivateAccessUserIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
  }
}

interface PrivateRouteChildren {
  PrivateAccessUserIndexRoute: typeof PrivateAccessUserIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAccessUserIndexRoute: PrivateAccessUserIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicAppAuthIndexRoute: typeof PublicAppAuthIndexRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAppAuthIndexRoute: PublicAppAuthIndexRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
