/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as IndexRouteImport } from './routes/index';
import { Route as PublicAuthIndexRouteImport } from './routes/_public/auth/index';
import { Route as PrivateSetUpCompanyIndexRouteImport } from './routes/_private/set-up-company/index';
import { Route as PrivateRegisterIndexRouteImport } from './routes/_private/register/index';
import { Route as PrivatePermissionsIndexRouteImport } from './routes/_private/permissions/index';
import { Route as PrivateMaintenanceIndexRouteImport } from './routes/_private/maintenance/index';
import { Route as PublicAuthUnlockRouteImport } from './routes/_public/auth/unlock';
import { Route as PublicAuthResetPasswordRouteImport } from './routes/_public/auth/reset-password';
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/auth/register';
import { Route as PrivateSetUpCompanySetupEmailIndexRouteImport } from './routes/_private/set-up-company/setup-email/index';
import { Route as PrivateSetUpCompanySetupApiExternalIndexRouteImport } from './routes/_private/set-up-company/setup-api-external/index';
import { Route as PrivateSetUpCompanyIntegrationListIndexRouteImport } from './routes/_private/set-up-company/integration-list/index';
import { Route as PrivateRegisterUserTypeIndexRouteImport } from './routes/_private/register/user-type/index';
import { Route as PrivateRegisterTypeFuelIndexRouteImport } from './routes/_private/register/type-fuel/index';
import { Route as PrivateRegisterSensorsIndexRouteImport } from './routes/_private/register/sensors/index';
import { Route as PrivateRegisterPlatformIndexRouteImport } from './routes/_private/register/platform/index';
import { Route as PrivatePermissionsUsersIndexRouteImport } from './routes/_private/permissions/users/index';
import { Route as PrivatePermissionsRolesIndexRouteImport } from './routes/_private/permissions/roles/index';
import { Route as PrivateMaintenanceMonitoringWearIndexRouteImport } from './routes/_private/maintenance/monitoring-wear/index';
import { Route as PrivateMaintenanceMonitoringPlansIndexRouteImport } from './routes/_private/maintenance/monitoring-plans/index';
import { Route as PrivateMaintenanceListOsDoneIndexRouteImport } from './routes/_private/maintenance/list-os-done/index';
import { Route as PrivateRegisterUserTypeAddRouteImport } from './routes/_private/register/user-type/add';
import { Route as PrivateRegisterTypeFuelAddRouteImport } from './routes/_private/register/type-fuel/add';
import { Route as PrivateRegisterSensorsAddRouteImport } from './routes/_private/register/sensors/add';
import { Route as PrivateRegisterPlatformAddRouteImport } from './routes/_private/register/platform/add';
import { Route as PrivatePermissionsUsersPermissionsAddRouteImport } from './routes/_private/permissions/users/permissions-add';
import { Route as PrivatePermissionsUsersAddRouteImport } from './routes/_private/permissions/users/add';
import { Route as PrivatePermissionsRolesAddRouteImport } from './routes/_private/permissions/roles/add';
import { Route as PrivatePermissionsUsersPasswordIndexRouteImport } from './routes/_private/permissions/users/password/index';
import { Route as PrivatePermissionsUsersEditIndexRouteImport } from './routes/_private/permissions/users/edit/index';
import { Route as PrivatePermissionsRolesUsersIndexRouteImport } from './routes/_private/permissions/roles/users/index';
import { Route as PrivatePermissionsRolesEditIndexRouteImport } from './routes/_private/permissions/roles/edit/index';
import { Route as PrivateMaintenanceListOsDoneViewIndexRouteImport } from './routes/_private/maintenance/list-os-done/view/index';

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicAuthIndexRoute = PublicAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateSetUpCompanyIndexRoute =
  PrivateSetUpCompanyIndexRouteImport.update({
    id: '/set-up-company/',
    path: '/set-up-company/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterIndexRoute = PrivateRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivatePermissionsIndexRoute = PrivatePermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateMaintenanceIndexRoute = PrivateMaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicAuthUnlockRoute = PublicAuthUnlockRouteImport.update({
  id: '/auth/unlock',
  path: '/auth/unlock',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAuthResetPasswordRoute = PublicAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateSetUpCompanySetupEmailIndexRoute =
  PrivateSetUpCompanySetupEmailIndexRouteImport.update({
    id: '/set-up-company/setup-email/',
    path: '/set-up-company/setup-email/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateSetUpCompanySetupApiExternalIndexRoute =
  PrivateSetUpCompanySetupApiExternalIndexRouteImport.update({
    id: '/set-up-company/setup-api-external/',
    path: '/set-up-company/setup-api-external/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateSetUpCompanyIntegrationListIndexRoute =
  PrivateSetUpCompanyIntegrationListIndexRouteImport.update({
    id: '/set-up-company/integration-list/',
    path: '/set-up-company/integration-list/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterUserTypeIndexRoute =
  PrivateRegisterUserTypeIndexRouteImport.update({
    id: '/register/user-type/',
    path: '/register/user-type/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterTypeFuelIndexRoute =
  PrivateRegisterTypeFuelIndexRouteImport.update({
    id: '/register/type-fuel/',
    path: '/register/type-fuel/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterSensorsIndexRoute =
  PrivateRegisterSensorsIndexRouteImport.update({
    id: '/register/sensors/',
    path: '/register/sensors/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterPlatformIndexRoute =
  PrivateRegisterPlatformIndexRouteImport.update({
    id: '/register/platform/',
    path: '/register/platform/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsUsersIndexRoute =
  PrivatePermissionsUsersIndexRouteImport.update({
    id: '/permissions/users/',
    path: '/permissions/users/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsRolesIndexRoute =
  PrivatePermissionsRolesIndexRouteImport.update({
    id: '/permissions/roles/',
    path: '/permissions/roles/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateMaintenanceMonitoringWearIndexRoute =
  PrivateMaintenanceMonitoringWearIndexRouteImport.update({
    id: '/maintenance/monitoring-wear/',
    path: '/maintenance/monitoring-wear/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateMaintenanceMonitoringPlansIndexRoute =
  PrivateMaintenanceMonitoringPlansIndexRouteImport.update({
    id: '/maintenance/monitoring-plans/',
    path: '/maintenance/monitoring-plans/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateMaintenanceListOsDoneIndexRoute =
  PrivateMaintenanceListOsDoneIndexRouteImport.update({
    id: '/maintenance/list-os-done/',
    path: '/maintenance/list-os-done/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterUserTypeAddRoute =
  PrivateRegisterUserTypeAddRouteImport.update({
    id: '/register/user-type/add',
    path: '/register/user-type/add',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterTypeFuelAddRoute =
  PrivateRegisterTypeFuelAddRouteImport.update({
    id: '/register/type-fuel/add',
    path: '/register/type-fuel/add',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterSensorsAddRoute =
  PrivateRegisterSensorsAddRouteImport.update({
    id: '/register/sensors/add',
    path: '/register/sensors/add',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateRegisterPlatformAddRoute =
  PrivateRegisterPlatformAddRouteImport.update({
    id: '/register/platform/add',
    path: '/register/platform/add',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsUsersPermissionsAddRoute =
  PrivatePermissionsUsersPermissionsAddRouteImport.update({
    id: '/permissions/users/permissions-add',
    path: '/permissions/users/permissions-add',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsUsersAddRoute =
  PrivatePermissionsUsersAddRouteImport.update({
    id: '/permissions/users/add',
    path: '/permissions/users/add',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsRolesAddRoute =
  PrivatePermissionsRolesAddRouteImport.update({
    id: '/permissions/roles/add',
    path: '/permissions/roles/add',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsUsersPasswordIndexRoute =
  PrivatePermissionsUsersPasswordIndexRouteImport.update({
    id: '/permissions/users/password/',
    path: '/permissions/users/password/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsUsersEditIndexRoute =
  PrivatePermissionsUsersEditIndexRouteImport.update({
    id: '/permissions/users/edit/',
    path: '/permissions/users/edit/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsRolesUsersIndexRoute =
  PrivatePermissionsRolesUsersIndexRouteImport.update({
    id: '/permissions/roles/users/',
    path: '/permissions/roles/users/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivatePermissionsRolesEditIndexRoute =
  PrivatePermissionsRolesEditIndexRouteImport.update({
    id: '/permissions/roles/edit/',
    path: '/permissions/roles/edit/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateMaintenanceListOsDoneViewIndexRoute =
  PrivateMaintenanceListOsDoneViewIndexRouteImport.update({
    id: '/maintenance/list-os-done/view/',
    path: '/maintenance/list-os-done/view/',
    getParentRoute: () => PrivateRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/auth/register': typeof PublicAuthRegisterRoute;
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute;
  '/auth/unlock': typeof PublicAuthUnlockRoute;
  '/maintenance': typeof PrivateMaintenanceIndexRoute;
  '/permissions': typeof PrivatePermissionsIndexRoute;
  '/register': typeof PrivateRegisterIndexRoute;
  '/set-up-company': typeof PrivateSetUpCompanyIndexRoute;
  '/auth': typeof PublicAuthIndexRoute;
  '/permissions/roles/add': typeof PrivatePermissionsRolesAddRoute;
  '/permissions/users/add': typeof PrivatePermissionsUsersAddRoute;
  '/permissions/users/permissions-add': typeof PrivatePermissionsUsersPermissionsAddRoute;
  '/register/platform/add': typeof PrivateRegisterPlatformAddRoute;
  '/register/sensors/add': typeof PrivateRegisterSensorsAddRoute;
  '/register/type-fuel/add': typeof PrivateRegisterTypeFuelAddRoute;
  '/register/user-type/add': typeof PrivateRegisterUserTypeAddRoute;
  '/maintenance/list-os-done': typeof PrivateMaintenanceListOsDoneIndexRoute;
  '/maintenance/monitoring-plans': typeof PrivateMaintenanceMonitoringPlansIndexRoute;
  '/maintenance/monitoring-wear': typeof PrivateMaintenanceMonitoringWearIndexRoute;
  '/permissions/roles': typeof PrivatePermissionsRolesIndexRoute;
  '/permissions/users': typeof PrivatePermissionsUsersIndexRoute;
  '/register/platform': typeof PrivateRegisterPlatformIndexRoute;
  '/register/sensors': typeof PrivateRegisterSensorsIndexRoute;
  '/register/type-fuel': typeof PrivateRegisterTypeFuelIndexRoute;
  '/register/user-type': typeof PrivateRegisterUserTypeIndexRoute;
  '/set-up-company/integration-list': typeof PrivateSetUpCompanyIntegrationListIndexRoute;
  '/set-up-company/setup-api-external': typeof PrivateSetUpCompanySetupApiExternalIndexRoute;
  '/set-up-company/setup-email': typeof PrivateSetUpCompanySetupEmailIndexRoute;
  '/maintenance/list-os-done/view': typeof PrivateMaintenanceListOsDoneViewIndexRoute;
  '/permissions/roles/edit': typeof PrivatePermissionsRolesEditIndexRoute;
  '/permissions/roles/users': typeof PrivatePermissionsRolesUsersIndexRoute;
  '/permissions/users/edit': typeof PrivatePermissionsUsersEditIndexRoute;
  '/permissions/users/password': typeof PrivatePermissionsUsersPasswordIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/auth/register': typeof PublicAuthRegisterRoute;
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute;
  '/auth/unlock': typeof PublicAuthUnlockRoute;
  '/maintenance': typeof PrivateMaintenanceIndexRoute;
  '/permissions': typeof PrivatePermissionsIndexRoute;
  '/register': typeof PrivateRegisterIndexRoute;
  '/set-up-company': typeof PrivateSetUpCompanyIndexRoute;
  '/auth': typeof PublicAuthIndexRoute;
  '/permissions/roles/add': typeof PrivatePermissionsRolesAddRoute;
  '/permissions/users/add': typeof PrivatePermissionsUsersAddRoute;
  '/permissions/users/permissions-add': typeof PrivatePermissionsUsersPermissionsAddRoute;
  '/register/platform/add': typeof PrivateRegisterPlatformAddRoute;
  '/register/sensors/add': typeof PrivateRegisterSensorsAddRoute;
  '/register/type-fuel/add': typeof PrivateRegisterTypeFuelAddRoute;
  '/register/user-type/add': typeof PrivateRegisterUserTypeAddRoute;
  '/maintenance/list-os-done': typeof PrivateMaintenanceListOsDoneIndexRoute;
  '/maintenance/monitoring-plans': typeof PrivateMaintenanceMonitoringPlansIndexRoute;
  '/maintenance/monitoring-wear': typeof PrivateMaintenanceMonitoringWearIndexRoute;
  '/permissions/roles': typeof PrivatePermissionsRolesIndexRoute;
  '/permissions/users': typeof PrivatePermissionsUsersIndexRoute;
  '/register/platform': typeof PrivateRegisterPlatformIndexRoute;
  '/register/sensors': typeof PrivateRegisterSensorsIndexRoute;
  '/register/type-fuel': typeof PrivateRegisterTypeFuelIndexRoute;
  '/register/user-type': typeof PrivateRegisterUserTypeIndexRoute;
  '/set-up-company/integration-list': typeof PrivateSetUpCompanyIntegrationListIndexRoute;
  '/set-up-company/setup-api-external': typeof PrivateSetUpCompanySetupApiExternalIndexRoute;
  '/set-up-company/setup-email': typeof PrivateSetUpCompanySetupEmailIndexRoute;
  '/maintenance/list-os-done/view': typeof PrivateMaintenanceListOsDoneViewIndexRoute;
  '/permissions/roles/edit': typeof PrivatePermissionsRolesEditIndexRoute;
  '/permissions/roles/users': typeof PrivatePermissionsRolesUsersIndexRoute;
  '/permissions/users/edit': typeof PrivatePermissionsUsersEditIndexRoute;
  '/permissions/users/password': typeof PrivatePermissionsUsersPasswordIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_private': typeof PrivateRouteWithChildren;
  '/_public': typeof PublicRouteWithChildren;
  '/_public/auth/register': typeof PublicAuthRegisterRoute;
  '/_public/auth/reset-password': typeof PublicAuthResetPasswordRoute;
  '/_public/auth/unlock': typeof PublicAuthUnlockRoute;
  '/_private/maintenance/': typeof PrivateMaintenanceIndexRoute;
  '/_private/permissions/': typeof PrivatePermissionsIndexRoute;
  '/_private/register/': typeof PrivateRegisterIndexRoute;
  '/_private/set-up-company/': typeof PrivateSetUpCompanyIndexRoute;
  '/_public/auth/': typeof PublicAuthIndexRoute;
  '/_private/permissions/roles/add': typeof PrivatePermissionsRolesAddRoute;
  '/_private/permissions/users/add': typeof PrivatePermissionsUsersAddRoute;
  '/_private/permissions/users/permissions-add': typeof PrivatePermissionsUsersPermissionsAddRoute;
  '/_private/register/platform/add': typeof PrivateRegisterPlatformAddRoute;
  '/_private/register/sensors/add': typeof PrivateRegisterSensorsAddRoute;
  '/_private/register/type-fuel/add': typeof PrivateRegisterTypeFuelAddRoute;
  '/_private/register/user-type/add': typeof PrivateRegisterUserTypeAddRoute;
  '/_private/maintenance/list-os-done/': typeof PrivateMaintenanceListOsDoneIndexRoute;
  '/_private/maintenance/monitoring-plans/': typeof PrivateMaintenanceMonitoringPlansIndexRoute;
  '/_private/maintenance/monitoring-wear/': typeof PrivateMaintenanceMonitoringWearIndexRoute;
  '/_private/permissions/roles/': typeof PrivatePermissionsRolesIndexRoute;
  '/_private/permissions/users/': typeof PrivatePermissionsUsersIndexRoute;
  '/_private/register/platform/': typeof PrivateRegisterPlatformIndexRoute;
  '/_private/register/sensors/': typeof PrivateRegisterSensorsIndexRoute;
  '/_private/register/type-fuel/': typeof PrivateRegisterTypeFuelIndexRoute;
  '/_private/register/user-type/': typeof PrivateRegisterUserTypeIndexRoute;
  '/_private/set-up-company/integration-list/': typeof PrivateSetUpCompanyIntegrationListIndexRoute;
  '/_private/set-up-company/setup-api-external/': typeof PrivateSetUpCompanySetupApiExternalIndexRoute;
  '/_private/set-up-company/setup-email/': typeof PrivateSetUpCompanySetupEmailIndexRoute;
  '/_private/maintenance/list-os-done/view/': typeof PrivateMaintenanceListOsDoneViewIndexRoute;
  '/_private/permissions/roles/edit/': typeof PrivatePermissionsRolesEditIndexRoute;
  '/_private/permissions/roles/users/': typeof PrivatePermissionsRolesUsersIndexRoute;
  '/_private/permissions/users/edit/': typeof PrivatePermissionsUsersEditIndexRoute;
  '/_private/permissions/users/password/': typeof PrivatePermissionsUsersPasswordIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/unlock'
    | '/maintenance'
    | '/permissions'
    | '/register'
    | '/set-up-company'
    | '/auth'
    | '/permissions/roles/add'
    | '/permissions/users/add'
    | '/permissions/users/permissions-add'
    | '/register/platform/add'
    | '/register/sensors/add'
    | '/register/type-fuel/add'
    | '/register/user-type/add'
    | '/maintenance/list-os-done'
    | '/maintenance/monitoring-plans'
    | '/maintenance/monitoring-wear'
    | '/permissions/roles'
    | '/permissions/users'
    | '/register/platform'
    | '/register/sensors'
    | '/register/type-fuel'
    | '/register/user-type'
    | '/set-up-company/integration-list'
    | '/set-up-company/setup-api-external'
    | '/set-up-company/setup-email'
    | '/maintenance/list-os-done/view'
    | '/permissions/roles/edit'
    | '/permissions/roles/users'
    | '/permissions/users/edit'
    | '/permissions/users/password';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/unlock'
    | '/maintenance'
    | '/permissions'
    | '/register'
    | '/set-up-company'
    | '/auth'
    | '/permissions/roles/add'
    | '/permissions/users/add'
    | '/permissions/users/permissions-add'
    | '/register/platform/add'
    | '/register/sensors/add'
    | '/register/type-fuel/add'
    | '/register/user-type/add'
    | '/maintenance/list-os-done'
    | '/maintenance/monitoring-plans'
    | '/maintenance/monitoring-wear'
    | '/permissions/roles'
    | '/permissions/users'
    | '/register/platform'
    | '/register/sensors'
    | '/register/type-fuel'
    | '/register/user-type'
    | '/set-up-company/integration-list'
    | '/set-up-company/setup-api-external'
    | '/set-up-company/setup-email'
    | '/maintenance/list-os-done/view'
    | '/permissions/roles/edit'
    | '/permissions/roles/users'
    | '/permissions/users/edit'
    | '/permissions/users/password';
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_public/auth/register'
    | '/_public/auth/reset-password'
    | '/_public/auth/unlock'
    | '/_private/maintenance/'
    | '/_private/permissions/'
    | '/_private/register/'
    | '/_private/set-up-company/'
    | '/_public/auth/'
    | '/_private/permissions/roles/add'
    | '/_private/permissions/users/add'
    | '/_private/permissions/users/permissions-add'
    | '/_private/register/platform/add'
    | '/_private/register/sensors/add'
    | '/_private/register/type-fuel/add'
    | '/_private/register/user-type/add'
    | '/_private/maintenance/list-os-done/'
    | '/_private/maintenance/monitoring-plans/'
    | '/_private/maintenance/monitoring-wear/'
    | '/_private/permissions/roles/'
    | '/_private/permissions/users/'
    | '/_private/register/platform/'
    | '/_private/register/sensors/'
    | '/_private/register/type-fuel/'
    | '/_private/register/user-type/'
    | '/_private/set-up-company/integration-list/'
    | '/_private/set-up-company/setup-api-external/'
    | '/_private/set-up-company/setup-email/'
    | '/_private/maintenance/list-os-done/view/'
    | '/_private/permissions/roles/edit/'
    | '/_private/permissions/roles/users/'
    | '/_private/permissions/users/edit/'
    | '/_private/permissions/users/password/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public/auth/': {
      id: '/_public/auth/';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof PublicAuthIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/set-up-company/': {
      id: '/_private/set-up-company/';
      path: '/set-up-company';
      fullPath: '/set-up-company';
      preLoaderRoute: typeof PrivateSetUpCompanyIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/': {
      id: '/_private/register/';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof PrivateRegisterIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/': {
      id: '/_private/permissions/';
      path: '/permissions';
      fullPath: '/permissions';
      preLoaderRoute: typeof PrivatePermissionsIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/maintenance/': {
      id: '/_private/maintenance/';
      path: '/maintenance';
      fullPath: '/maintenance';
      preLoaderRoute: typeof PrivateMaintenanceIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/auth/unlock': {
      id: '/_public/auth/unlock';
      path: '/auth/unlock';
      fullPath: '/auth/unlock';
      preLoaderRoute: typeof PublicAuthUnlockRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/auth/reset-password': {
      id: '/_public/auth/reset-password';
      path: '/auth/reset-password';
      fullPath: '/auth/reset-password';
      preLoaderRoute: typeof PublicAuthResetPasswordRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/auth/register': {
      id: '/_public/auth/register';
      path: '/auth/register';
      fullPath: '/auth/register';
      preLoaderRoute: typeof PublicAuthRegisterRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/set-up-company/setup-email/': {
      id: '/_private/set-up-company/setup-email/';
      path: '/set-up-company/setup-email';
      fullPath: '/set-up-company/setup-email';
      preLoaderRoute: typeof PrivateSetUpCompanySetupEmailIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/set-up-company/setup-api-external/': {
      id: '/_private/set-up-company/setup-api-external/';
      path: '/set-up-company/setup-api-external';
      fullPath: '/set-up-company/setup-api-external';
      preLoaderRoute: typeof PrivateSetUpCompanySetupApiExternalIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/set-up-company/integration-list/': {
      id: '/_private/set-up-company/integration-list/';
      path: '/set-up-company/integration-list';
      fullPath: '/set-up-company/integration-list';
      preLoaderRoute: typeof PrivateSetUpCompanyIntegrationListIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/user-type/': {
      id: '/_private/register/user-type/';
      path: '/register/user-type';
      fullPath: '/register/user-type';
      preLoaderRoute: typeof PrivateRegisterUserTypeIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/type-fuel/': {
      id: '/_private/register/type-fuel/';
      path: '/register/type-fuel';
      fullPath: '/register/type-fuel';
      preLoaderRoute: typeof PrivateRegisterTypeFuelIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/sensors/': {
      id: '/_private/register/sensors/';
      path: '/register/sensors';
      fullPath: '/register/sensors';
      preLoaderRoute: typeof PrivateRegisterSensorsIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/platform/': {
      id: '/_private/register/platform/';
      path: '/register/platform';
      fullPath: '/register/platform';
      preLoaderRoute: typeof PrivateRegisterPlatformIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/users/': {
      id: '/_private/permissions/users/';
      path: '/permissions/users';
      fullPath: '/permissions/users';
      preLoaderRoute: typeof PrivatePermissionsUsersIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/roles/': {
      id: '/_private/permissions/roles/';
      path: '/permissions/roles';
      fullPath: '/permissions/roles';
      preLoaderRoute: typeof PrivatePermissionsRolesIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/maintenance/monitoring-wear/': {
      id: '/_private/maintenance/monitoring-wear/';
      path: '/maintenance/monitoring-wear';
      fullPath: '/maintenance/monitoring-wear';
      preLoaderRoute: typeof PrivateMaintenanceMonitoringWearIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/maintenance/monitoring-plans/': {
      id: '/_private/maintenance/monitoring-plans/';
      path: '/maintenance/monitoring-plans';
      fullPath: '/maintenance/monitoring-plans';
      preLoaderRoute: typeof PrivateMaintenanceMonitoringPlansIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/maintenance/list-os-done/': {
      id: '/_private/maintenance/list-os-done/';
      path: '/maintenance/list-os-done';
      fullPath: '/maintenance/list-os-done';
      preLoaderRoute: typeof PrivateMaintenanceListOsDoneIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/user-type/add': {
      id: '/_private/register/user-type/add';
      path: '/register/user-type/add';
      fullPath: '/register/user-type/add';
      preLoaderRoute: typeof PrivateRegisterUserTypeAddRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/type-fuel/add': {
      id: '/_private/register/type-fuel/add';
      path: '/register/type-fuel/add';
      fullPath: '/register/type-fuel/add';
      preLoaderRoute: typeof PrivateRegisterTypeFuelAddRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/sensors/add': {
      id: '/_private/register/sensors/add';
      path: '/register/sensors/add';
      fullPath: '/register/sensors/add';
      preLoaderRoute: typeof PrivateRegisterSensorsAddRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/register/platform/add': {
      id: '/_private/register/platform/add';
      path: '/register/platform/add';
      fullPath: '/register/platform/add';
      preLoaderRoute: typeof PrivateRegisterPlatformAddRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/users/permissions-add': {
      id: '/_private/permissions/users/permissions-add';
      path: '/permissions/users/permissions-add';
      fullPath: '/permissions/users/permissions-add';
      preLoaderRoute: typeof PrivatePermissionsUsersPermissionsAddRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/users/add': {
      id: '/_private/permissions/users/add';
      path: '/permissions/users/add';
      fullPath: '/permissions/users/add';
      preLoaderRoute: typeof PrivatePermissionsUsersAddRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/roles/add': {
      id: '/_private/permissions/roles/add';
      path: '/permissions/roles/add';
      fullPath: '/permissions/roles/add';
      preLoaderRoute: typeof PrivatePermissionsRolesAddRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/users/password/': {
      id: '/_private/permissions/users/password/';
      path: '/permissions/users/password';
      fullPath: '/permissions/users/password';
      preLoaderRoute: typeof PrivatePermissionsUsersPasswordIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/users/edit/': {
      id: '/_private/permissions/users/edit/';
      path: '/permissions/users/edit';
      fullPath: '/permissions/users/edit';
      preLoaderRoute: typeof PrivatePermissionsUsersEditIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/roles/users/': {
      id: '/_private/permissions/roles/users/';
      path: '/permissions/roles/users';
      fullPath: '/permissions/roles/users';
      preLoaderRoute: typeof PrivatePermissionsRolesUsersIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/permissions/roles/edit/': {
      id: '/_private/permissions/roles/edit/';
      path: '/permissions/roles/edit';
      fullPath: '/permissions/roles/edit';
      preLoaderRoute: typeof PrivatePermissionsRolesEditIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/maintenance/list-os-done/view/': {
      id: '/_private/maintenance/list-os-done/view/';
      path: '/maintenance/list-os-done/view';
      fullPath: '/maintenance/list-os-done/view';
      preLoaderRoute: typeof PrivateMaintenanceListOsDoneViewIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
  }
}

interface PrivateRouteChildren {
  PrivateMaintenanceIndexRoute: typeof PrivateMaintenanceIndexRoute;
  PrivatePermissionsIndexRoute: typeof PrivatePermissionsIndexRoute;
  PrivateRegisterIndexRoute: typeof PrivateRegisterIndexRoute;
  PrivateSetUpCompanyIndexRoute: typeof PrivateSetUpCompanyIndexRoute;
  PrivatePermissionsRolesAddRoute: typeof PrivatePermissionsRolesAddRoute;
  PrivatePermissionsUsersAddRoute: typeof PrivatePermissionsUsersAddRoute;
  PrivatePermissionsUsersPermissionsAddRoute: typeof PrivatePermissionsUsersPermissionsAddRoute;
  PrivateRegisterPlatformAddRoute: typeof PrivateRegisterPlatformAddRoute;
  PrivateRegisterSensorsAddRoute: typeof PrivateRegisterSensorsAddRoute;
  PrivateRegisterTypeFuelAddRoute: typeof PrivateRegisterTypeFuelAddRoute;
  PrivateRegisterUserTypeAddRoute: typeof PrivateRegisterUserTypeAddRoute;
  PrivateMaintenanceListOsDoneIndexRoute: typeof PrivateMaintenanceListOsDoneIndexRoute;
  PrivateMaintenanceMonitoringPlansIndexRoute: typeof PrivateMaintenanceMonitoringPlansIndexRoute;
  PrivateMaintenanceMonitoringWearIndexRoute: typeof PrivateMaintenanceMonitoringWearIndexRoute;
  PrivatePermissionsRolesIndexRoute: typeof PrivatePermissionsRolesIndexRoute;
  PrivatePermissionsUsersIndexRoute: typeof PrivatePermissionsUsersIndexRoute;
  PrivateRegisterPlatformIndexRoute: typeof PrivateRegisterPlatformIndexRoute;
  PrivateRegisterSensorsIndexRoute: typeof PrivateRegisterSensorsIndexRoute;
  PrivateRegisterTypeFuelIndexRoute: typeof PrivateRegisterTypeFuelIndexRoute;
  PrivateRegisterUserTypeIndexRoute: typeof PrivateRegisterUserTypeIndexRoute;
  PrivateSetUpCompanyIntegrationListIndexRoute: typeof PrivateSetUpCompanyIntegrationListIndexRoute;
  PrivateSetUpCompanySetupApiExternalIndexRoute: typeof PrivateSetUpCompanySetupApiExternalIndexRoute;
  PrivateSetUpCompanySetupEmailIndexRoute: typeof PrivateSetUpCompanySetupEmailIndexRoute;
  PrivateMaintenanceListOsDoneViewIndexRoute: typeof PrivateMaintenanceListOsDoneViewIndexRoute;
  PrivatePermissionsRolesEditIndexRoute: typeof PrivatePermissionsRolesEditIndexRoute;
  PrivatePermissionsRolesUsersIndexRoute: typeof PrivatePermissionsRolesUsersIndexRoute;
  PrivatePermissionsUsersEditIndexRoute: typeof PrivatePermissionsUsersEditIndexRoute;
  PrivatePermissionsUsersPasswordIndexRoute: typeof PrivatePermissionsUsersPasswordIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateMaintenanceIndexRoute: PrivateMaintenanceIndexRoute,
  PrivatePermissionsIndexRoute: PrivatePermissionsIndexRoute,
  PrivateRegisterIndexRoute: PrivateRegisterIndexRoute,
  PrivateSetUpCompanyIndexRoute: PrivateSetUpCompanyIndexRoute,
  PrivatePermissionsRolesAddRoute: PrivatePermissionsRolesAddRoute,
  PrivatePermissionsUsersAddRoute: PrivatePermissionsUsersAddRoute,
  PrivatePermissionsUsersPermissionsAddRoute:
    PrivatePermissionsUsersPermissionsAddRoute,
  PrivateRegisterPlatformAddRoute: PrivateRegisterPlatformAddRoute,
  PrivateRegisterSensorsAddRoute: PrivateRegisterSensorsAddRoute,
  PrivateRegisterTypeFuelAddRoute: PrivateRegisterTypeFuelAddRoute,
  PrivateRegisterUserTypeAddRoute: PrivateRegisterUserTypeAddRoute,
  PrivateMaintenanceListOsDoneIndexRoute:
    PrivateMaintenanceListOsDoneIndexRoute,
  PrivateMaintenanceMonitoringPlansIndexRoute:
    PrivateMaintenanceMonitoringPlansIndexRoute,
  PrivateMaintenanceMonitoringWearIndexRoute:
    PrivateMaintenanceMonitoringWearIndexRoute,
  PrivatePermissionsRolesIndexRoute: PrivatePermissionsRolesIndexRoute,
  PrivatePermissionsUsersIndexRoute: PrivatePermissionsUsersIndexRoute,
  PrivateRegisterPlatformIndexRoute: PrivateRegisterPlatformIndexRoute,
  PrivateRegisterSensorsIndexRoute: PrivateRegisterSensorsIndexRoute,
  PrivateRegisterTypeFuelIndexRoute: PrivateRegisterTypeFuelIndexRoute,
  PrivateRegisterUserTypeIndexRoute: PrivateRegisterUserTypeIndexRoute,
  PrivateSetUpCompanyIntegrationListIndexRoute:
    PrivateSetUpCompanyIntegrationListIndexRoute,
  PrivateSetUpCompanySetupApiExternalIndexRoute:
    PrivateSetUpCompanySetupApiExternalIndexRoute,
  PrivateSetUpCompanySetupEmailIndexRoute:
    PrivateSetUpCompanySetupEmailIndexRoute,
  PrivateMaintenanceListOsDoneViewIndexRoute:
    PrivateMaintenanceListOsDoneViewIndexRoute,
  PrivatePermissionsRolesEditIndexRoute: PrivatePermissionsRolesEditIndexRoute,
  PrivatePermissionsRolesUsersIndexRoute:
    PrivatePermissionsRolesUsersIndexRoute,
  PrivatePermissionsUsersEditIndexRoute: PrivatePermissionsUsersEditIndexRoute,
  PrivatePermissionsUsersPasswordIndexRoute:
    PrivatePermissionsUsersPasswordIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute;
  PublicAuthResetPasswordRoute: typeof PublicAuthResetPasswordRoute;
  PublicAuthUnlockRoute: typeof PublicAuthUnlockRoute;
  PublicAuthIndexRoute: typeof PublicAuthIndexRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthResetPasswordRoute: PublicAuthResetPasswordRoute,
  PublicAuthUnlockRoute: PublicAuthUnlockRoute,
  PublicAuthIndexRoute: PublicAuthIndexRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
