/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as PrivateFinancialIdRouteImport } from './routes/_private/financial/$id';
import { Route as PrivateFinancialAddRouteImport } from './routes/_private/financial/add';
import { Route as PrivateFinancialIndexRouteImport } from './routes/_private/financial/index';
import { Route as PrivateSettingsAccessIndexRouteImport } from './routes/_private/settings/access/index';
import { Route as PrivateSettingsClinicIndexRouteImport } from './routes/_private/settings/clinic/index';
import { Route as PrivateSettingsIndexRouteImport } from './routes/_private/settings/index';
import { Route as PrivateSettingsInviteIndexRouteImport } from './routes/_private/settings/invite/index';
import { Route as PrivateSettingsPermissionsIndexRouteImport } from './routes/_private/settings/permissions/index';
import { Route as PrivateSettingsProceduresIndexRouteImport } from './routes/_private/settings/procedures/index';
import { Route as PrivateSettingsProfileIndexRouteImport } from './routes/_private/settings/profile/index';
import { Route as PrivateSettingsRouteRouteImport } from './routes/_private/settings/route';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as PublicAuthFinishSignupCodeIndexRouteImport } from './routes/_public/auth/finish-signup/$code/index';
import { Route as PublicAuthIndexRouteImport } from './routes/_public/auth/index';
import { Route as PublicAuthNewPasswordCodeIndexRouteImport } from './routes/_public/auth/new-password/$code/index';
import { Route as PublicAuthRecoveryIndexRouteImport } from './routes/_public/auth/recovery/index';
import { Route as PublicAuthSignupIndexRouteImport } from './routes/_public/auth/signup/index';
import { Route as PublicScheduleCodeIndexRouteImport } from './routes/_public/schedule/$code/index';
import { Route as IndexRouteImport } from './routes/index';

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateSettingsRouteRoute = PrivateSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicAuthIndexRoute = PublicAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateSettingsIndexRoute = PrivateSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateSettingsRouteRoute,
} as any);
const PrivateFinancialIndexRoute = PrivateFinancialIndexRouteImport.update({
  id: '/financial/',
  path: '/financial/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateFinancialAddRoute = PrivateFinancialAddRouteImport.update({
  id: '/financial/add',
  path: '/financial/add',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateFinancialIdRoute = PrivateFinancialIdRouteImport.update({
  id: '/financial/$id',
  path: '/financial/$id',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicScheduleCodeIndexRoute = PublicScheduleCodeIndexRouteImport.update({
  id: '/schedule/$code/',
  path: '/schedule/$code/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAuthSignupIndexRoute = PublicAuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAuthRecoveryIndexRoute = PublicAuthRecoveryIndexRouteImport.update({
  id: '/auth/recovery/',
  path: '/auth/recovery/',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateSettingsProfileIndexRoute =
  PrivateSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => PrivateSettingsRouteRoute,
  } as any);
const PrivateSettingsProceduresIndexRoute =
  PrivateSettingsProceduresIndexRouteImport.update({
    id: '/procedures/',
    path: '/procedures/',
    getParentRoute: () => PrivateSettingsRouteRoute,
  } as any);
const PrivateSettingsPermissionsIndexRoute =
  PrivateSettingsPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => PrivateSettingsRouteRoute,
  } as any);
const PrivateSettingsInviteIndexRoute =
  PrivateSettingsInviteIndexRouteImport.update({
    id: '/invite/',
    path: '/invite/',
    getParentRoute: () => PrivateSettingsRouteRoute,
  } as any);
const PrivateSettingsClinicIndexRoute =
  PrivateSettingsClinicIndexRouteImport.update({
    id: '/clinic/',
    path: '/clinic/',
    getParentRoute: () => PrivateSettingsRouteRoute,
  } as any);
const PrivateSettingsAccessIndexRoute =
  PrivateSettingsAccessIndexRouteImport.update({
    id: '/access/',
    path: '/access/',
    getParentRoute: () => PrivateSettingsRouteRoute,
  } as any);
const PublicAuthNewPasswordCodeIndexRoute =
  PublicAuthNewPasswordCodeIndexRouteImport.update({
    id: '/auth/new-password/$code/',
    path: '/auth/new-password/$code/',
    getParentRoute: () => PublicRoute,
  } as any);
const PublicAuthFinishSignupCodeIndexRoute =
  PublicAuthFinishSignupCodeIndexRouteImport.update({
    id: '/auth/finish-signup/$code/',
    path: '/auth/finish-signup/$code/',
    getParentRoute: () => PublicRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/settings': typeof PrivateSettingsRouteRouteWithChildren;
  '/financial/$id': typeof PrivateFinancialIdRoute;
  '/financial/add': typeof PrivateFinancialAddRoute;
  '/financial/': typeof PrivateFinancialIndexRoute;
  '/settings/': typeof PrivateSettingsIndexRoute;
  '/auth/': typeof PublicAuthIndexRoute;
  '/settings/access/': typeof PrivateSettingsAccessIndexRoute;
  '/settings/clinic/': typeof PrivateSettingsClinicIndexRoute;
  '/settings/invite/': typeof PrivateSettingsInviteIndexRoute;
  '/settings/permissions/': typeof PrivateSettingsPermissionsIndexRoute;
  '/settings/procedures/': typeof PrivateSettingsProceduresIndexRoute;
  '/settings/profile/': typeof PrivateSettingsProfileIndexRoute;
  '/auth/recovery/': typeof PublicAuthRecoveryIndexRoute;
  '/auth/signup/': typeof PublicAuthSignupIndexRoute;
  '/schedule/$code/': typeof PublicScheduleCodeIndexRoute;
  '/auth/finish-signup/$code/': typeof PublicAuthFinishSignupCodeIndexRoute;
  '/auth/new-password/$code/': typeof PublicAuthNewPasswordCodeIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/financial/$id': typeof PrivateFinancialIdRoute;
  '/financial/add': typeof PrivateFinancialAddRoute;
  '/financial': typeof PrivateFinancialIndexRoute;
  '/settings': typeof PrivateSettingsIndexRoute;
  '/auth': typeof PublicAuthIndexRoute;
  '/settings/access': typeof PrivateSettingsAccessIndexRoute;
  '/settings/clinic': typeof PrivateSettingsClinicIndexRoute;
  '/settings/invite': typeof PrivateSettingsInviteIndexRoute;
  '/settings/permissions': typeof PrivateSettingsPermissionsIndexRoute;
  '/settings/procedures': typeof PrivateSettingsProceduresIndexRoute;
  '/settings/profile': typeof PrivateSettingsProfileIndexRoute;
  '/auth/recovery': typeof PublicAuthRecoveryIndexRoute;
  '/auth/signup': typeof PublicAuthSignupIndexRoute;
  '/schedule/$code': typeof PublicScheduleCodeIndexRoute;
  '/auth/finish-signup/$code': typeof PublicAuthFinishSignupCodeIndexRoute;
  '/auth/new-password/$code': typeof PublicAuthNewPasswordCodeIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_private': typeof PrivateRouteWithChildren;
  '/_public': typeof PublicRouteWithChildren;
  '/_private/settings': typeof PrivateSettingsRouteRouteWithChildren;
  '/_private/financial/$id': typeof PrivateFinancialIdRoute;
  '/_private/financial/add': typeof PrivateFinancialAddRoute;
  '/_private/financial/': typeof PrivateFinancialIndexRoute;
  '/_private/settings/': typeof PrivateSettingsIndexRoute;
  '/_public/auth/': typeof PublicAuthIndexRoute;
  '/_private/settings/access/': typeof PrivateSettingsAccessIndexRoute;
  '/_private/settings/clinic/': typeof PrivateSettingsClinicIndexRoute;
  '/_private/settings/invite/': typeof PrivateSettingsInviteIndexRoute;
  '/_private/settings/permissions/': typeof PrivateSettingsPermissionsIndexRoute;
  '/_private/settings/procedures/': typeof PrivateSettingsProceduresIndexRoute;
  '/_private/settings/profile/': typeof PrivateSettingsProfileIndexRoute;
  '/_public/auth/recovery/': typeof PublicAuthRecoveryIndexRoute;
  '/_public/auth/signup/': typeof PublicAuthSignupIndexRoute;
  '/_public/schedule/$code/': typeof PublicScheduleCodeIndexRoute;
  '/_public/auth/finish-signup/$code/': typeof PublicAuthFinishSignupCodeIndexRoute;
  '/_public/auth/new-password/$code/': typeof PublicAuthNewPasswordCodeIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/settings'
    | '/financial/$id'
    | '/financial/add'
    | '/financial/'
    | '/settings/'
    | '/auth/'
    | '/settings/access/'
    | '/settings/clinic/'
    | '/settings/invite/'
    | '/settings/permissions/'
    | '/settings/procedures/'
    | '/settings/profile/'
    | '/auth/recovery/'
    | '/auth/signup/'
    | '/schedule/$code/'
    | '/auth/finish-signup/$code/'
    | '/auth/new-password/$code/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/financial/$id'
    | '/financial/add'
    | '/financial'
    | '/settings'
    | '/auth'
    | '/settings/access'
    | '/settings/clinic'
    | '/settings/invite'
    | '/settings/permissions'
    | '/settings/procedures'
    | '/settings/profile'
    | '/auth/recovery'
    | '/auth/signup'
    | '/schedule/$code'
    | '/auth/finish-signup/$code'
    | '/auth/new-password/$code';
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/settings'
    | '/_private/financial/$id'
    | '/_private/financial/add'
    | '/_private/financial/'
    | '/_private/settings/'
    | '/_public/auth/'
    | '/_private/settings/access/'
    | '/_private/settings/clinic/'
    | '/_private/settings/invite/'
    | '/_private/settings/permissions/'
    | '/_private/settings/procedures/'
    | '/_private/settings/profile/'
    | '/_public/auth/recovery/'
    | '/_public/auth/signup/'
    | '/_public/schedule/$code/'
    | '/_public/auth/finish-signup/$code/'
    | '/_public/auth/new-password/$code/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private/settings': {
      id: '/_private/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof PrivateSettingsRouteRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/auth/': {
      id: '/_public/auth/';
      path: '/auth';
      fullPath: '/auth/';
      preLoaderRoute: typeof PublicAuthIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/settings/': {
      id: '/_private/settings/';
      path: '/';
      fullPath: '/settings/';
      preLoaderRoute: typeof PrivateSettingsIndexRouteImport;
      parentRoute: typeof PrivateSettingsRouteRoute;
    };
    '/_private/financial/': {
      id: '/_private/financial/';
      path: '/financial';
      fullPath: '/financial/';
      preLoaderRoute: typeof PrivateFinancialIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/financial/add': {
      id: '/_private/financial/add';
      path: '/financial/add';
      fullPath: '/financial/add';
      preLoaderRoute: typeof PrivateFinancialAddRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/financial/$id': {
      id: '/_private/financial/$id';
      path: '/financial/$id';
      fullPath: '/financial/$id';
      preLoaderRoute: typeof PrivateFinancialIdRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/schedule/$code/': {
      id: '/_public/schedule/$code/';
      path: '/schedule/$code';
      fullPath: '/schedule/$code/';
      preLoaderRoute: typeof PublicScheduleCodeIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/auth/signup/': {
      id: '/_public/auth/signup/';
      path: '/auth/signup';
      fullPath: '/auth/signup/';
      preLoaderRoute: typeof PublicAuthSignupIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/auth/recovery/': {
      id: '/_public/auth/recovery/';
      path: '/auth/recovery';
      fullPath: '/auth/recovery/';
      preLoaderRoute: typeof PublicAuthRecoveryIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/settings/profile/': {
      id: '/_private/settings/profile/';
      path: '/profile';
      fullPath: '/settings/profile/';
      preLoaderRoute: typeof PrivateSettingsProfileIndexRouteImport;
      parentRoute: typeof PrivateSettingsRouteRoute;
    };
    '/_private/settings/procedures/': {
      id: '/_private/settings/procedures/';
      path: '/procedures';
      fullPath: '/settings/procedures/';
      preLoaderRoute: typeof PrivateSettingsProceduresIndexRouteImport;
      parentRoute: typeof PrivateSettingsRouteRoute;
    };
    '/_private/settings/permissions/': {
      id: '/_private/settings/permissions/';
      path: '/permissions';
      fullPath: '/settings/permissions/';
      preLoaderRoute: typeof PrivateSettingsPermissionsIndexRouteImport;
      parentRoute: typeof PrivateSettingsRouteRoute;
    };
    '/_private/settings/invite/': {
      id: '/_private/settings/invite/';
      path: '/invite';
      fullPath: '/settings/invite/';
      preLoaderRoute: typeof PrivateSettingsInviteIndexRouteImport;
      parentRoute: typeof PrivateSettingsRouteRoute;
    };
    '/_private/settings/clinic/': {
      id: '/_private/settings/clinic/';
      path: '/clinic';
      fullPath: '/settings/clinic/';
      preLoaderRoute: typeof PrivateSettingsClinicIndexRouteImport;
      parentRoute: typeof PrivateSettingsRouteRoute;
    };
    '/_private/settings/access/': {
      id: '/_private/settings/access/';
      path: '/access';
      fullPath: '/settings/access/';
      preLoaderRoute: typeof PrivateSettingsAccessIndexRouteImport;
      parentRoute: typeof PrivateSettingsRouteRoute;
    };
    '/_public/auth/new-password/$code/': {
      id: '/_public/auth/new-password/$code/';
      path: '/auth/new-password/$code';
      fullPath: '/auth/new-password/$code/';
      preLoaderRoute: typeof PublicAuthNewPasswordCodeIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/auth/finish-signup/$code/': {
      id: '/_public/auth/finish-signup/$code/';
      path: '/auth/finish-signup/$code';
      fullPath: '/auth/finish-signup/$code/';
      preLoaderRoute: typeof PublicAuthFinishSignupCodeIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
  }
}

interface PrivateSettingsRouteRouteChildren {
  PrivateSettingsIndexRoute: typeof PrivateSettingsIndexRoute;
  PrivateSettingsAccessIndexRoute: typeof PrivateSettingsAccessIndexRoute;
  PrivateSettingsClinicIndexRoute: typeof PrivateSettingsClinicIndexRoute;
  PrivateSettingsInviteIndexRoute: typeof PrivateSettingsInviteIndexRoute;
  PrivateSettingsPermissionsIndexRoute: typeof PrivateSettingsPermissionsIndexRoute;
  PrivateSettingsProceduresIndexRoute: typeof PrivateSettingsProceduresIndexRoute;
  PrivateSettingsProfileIndexRoute: typeof PrivateSettingsProfileIndexRoute;
}

const PrivateSettingsRouteRouteChildren: PrivateSettingsRouteRouteChildren = {
  PrivateSettingsIndexRoute: PrivateSettingsIndexRoute,
  PrivateSettingsAccessIndexRoute: PrivateSettingsAccessIndexRoute,
  PrivateSettingsClinicIndexRoute: PrivateSettingsClinicIndexRoute,
  PrivateSettingsInviteIndexRoute: PrivateSettingsInviteIndexRoute,
  PrivateSettingsPermissionsIndexRoute: PrivateSettingsPermissionsIndexRoute,
  PrivateSettingsProceduresIndexRoute: PrivateSettingsProceduresIndexRoute,
  PrivateSettingsProfileIndexRoute: PrivateSettingsProfileIndexRoute,
};

const PrivateSettingsRouteRouteWithChildren =
  PrivateSettingsRouteRoute._addFileChildren(PrivateSettingsRouteRouteChildren);

interface PrivateRouteChildren {
  PrivateSettingsRouteRoute: typeof PrivateSettingsRouteRouteWithChildren;
  PrivateFinancialIdRoute: typeof PrivateFinancialIdRoute;
  PrivateFinancialAddRoute: typeof PrivateFinancialAddRoute;
  PrivateFinancialIndexRoute: typeof PrivateFinancialIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateSettingsRouteRoute: PrivateSettingsRouteRouteWithChildren,
  PrivateFinancialIdRoute: PrivateFinancialIdRoute,
  PrivateFinancialAddRoute: PrivateFinancialAddRoute,
  PrivateFinancialIndexRoute: PrivateFinancialIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicAuthIndexRoute: typeof PublicAuthIndexRoute;
  PublicAuthRecoveryIndexRoute: typeof PublicAuthRecoveryIndexRoute;
  PublicAuthSignupIndexRoute: typeof PublicAuthSignupIndexRoute;
  PublicScheduleCodeIndexRoute: typeof PublicScheduleCodeIndexRoute;
  PublicAuthFinishSignupCodeIndexRoute: typeof PublicAuthFinishSignupCodeIndexRoute;
  PublicAuthNewPasswordCodeIndexRoute: typeof PublicAuthNewPasswordCodeIndexRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthIndexRoute: PublicAuthIndexRoute,
  PublicAuthRecoveryIndexRoute: PublicAuthRecoveryIndexRoute,
  PublicAuthSignupIndexRoute: PublicAuthSignupIndexRoute,
  PublicScheduleCodeIndexRoute: PublicScheduleCodeIndexRoute,
  PublicAuthFinishSignupCodeIndexRoute: PublicAuthFinishSignupCodeIndexRoute,
  PublicAuthNewPasswordCodeIndexRoute: PublicAuthNewPasswordCodeIndexRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
