export const UI_CONSTANTS = {
  // Animation & Timing
  SIMULATED_ACCORDION_DELAY: 800,

  // Layout & Sizing
  SHEET_SIDE_WIDTH: 'sm:max-w-2xl',
  SCROLL_AREA_OFFSET: 200,
  SKELETON_HEIGHT: 'h-12',
  CHAT_APP_ICON_SIZE: 20,
  BACKEND_SEARCH_ICON_SIZE: 12,

  // Input
  MAX_FILE_NAME_LENGTH: 32,
};
