import { optionsOperation } from "./Options";

export const getFields = ({
  eventsRef,
  group,
  data,
  status,
  hasPermissionViewFinancial
}) => {
  let fields = [
    // {
    //   id: 9,
    //   name: "contractGroup",
    //   description: "Contrato",
    //   datatype: "group",
    //   size: 12,
    //   fields: [
    //     {
    //       id: 11,
    //       name: "typeAsset",
    //       description: "Tipo",
    //       datatype: "textView",
    //       size: 2,
    //       properties: {
    //         readOnly: true,
    //       },
    //       fields: [],
    //       isShowInList: true,
    //       isVisiblePublic: true,
    //     },
    //     {
    //       id: 12,
    //       name: "enterpriseName",
    //       description: "Responsabilidade",
    //       datatype: "textView",
    //       size: 2,
    //       properties: {
    //         readOnly: true,
    //       },
    //       fields: [],
    //       isShowInList: true,
    //       isVisiblePublic: true,
    //     },
    //     {
    //       id: 13,
    //       name: "customer",
    //       description: "Cliente",
    //       datatype: "textView",
    //       size: 3,
    //       properties: {
    //         readOnly: true,
    //       },
    //       fields: [],
    //       isShowInList: true,
    //       isVisiblePublic: true,
    //     },
    //     {
    //       id: 14,
    //       name: "priceFormatted",
    //       description: "Diária",
    //       datatype: "textView",
    //       size: 2,
    //       isVisiblePublic: true,
    //       properties: {
    //         readOnly: true,
    //       },
    //     },
    //   ],
    // },
    {
      id: 9,
      name: "eventGroup",
      description: "Evento",
      datatype: "group",
      size: 12,
      fields: [
        {
          id: 1,
          name: "embarcacao",
          description: "Embarcação",
          datatype: "selectMachine",
          size: 6,
          isRequired: true,
          fields: [],
          isShowInList: true,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 10,
          name: "status",
          description: "Status",
          datatype: "select",
          size: status === "downtime-parcial" ? 4 : 6,
          properties: {
            optionsMap: optionsOperation,
          },
          fields: [],
          isShowInList: true,
          isVisiblePublic: true,
        },
        status === "downtime-parcial" && {
          id: 11,
          name: "factor",
          description: "Fator",
          datatype: "number",
          properties: {
            sizeDecimals: 2,
            min: 0,
            max: 100,
            unit: "%",
          },
          size: 2,
          fields: [],
          isShowInList: true,
          isVisiblePublic: true,
        },
        {
          id: 2,
          name: "inicio",
          description: "Início",
          datatype: "datetime",
          size: 6,
          isRequired: true,
          properties: {
            useDateNowDefault: true,
          },
          fields: [],
          isShowInList: true,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 3,
          name: "fim",
          description: "Fim",
          datatype: "datetime",
          size: 6,
          isRequired: false,
          fields: [],
          isShowInList: true,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 5,
          name: "grupo",
          description: "Grupo",
          datatype: "select",
          size: 4,
          isRequired: false,
          properties: {
            isClearable: true,
            options: group
              .sort((a, b) => a.name?.localeCompare(b.name))
              .map((x) => x.name),
          },
          fields: [],
          isShowInList: true,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 6,
          name: "subgrupo",
          description: "Subgrupo",
          datatype: "select",
          size: 4,
          properties: {
            isClearable: true,
            options: group
              .find((x) => x.name === data.grupo)
              ?.subgroup?.map((x) => x.name)
              ?.sort((a, b) => a?.localeCompare(b)),
          },
          fields: [],
          isShowInList: true,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 7,
          name: "evento",
          description: "Evento",
          datatype: "select",
          size: 4,
          properties: {
            isClearable: true,
            options: eventsRef.current
              ?.map((x) => x.description)
              ?.sort((a, b) => a?.localeCompare(b)),
          },
          fields: [],
          isShowInList: true,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 8,
          name: "local",
          description: "Local",
          datatype: "text",
          size: 12,
          fields: [],
          isShowInList: false,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 8,
          name: "description",
          description: "Descrição",
          datatype: "textArea",
          size: 12,
          fields: [],
          isShowInList: false,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 8,
          name: "observacao",
          description: "Observação",
          datatype: "textArea",
          size: 12,
          fields: [],
          isShowInList: false,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 8,
          name: "carta",
          description: "Carta",
          datatype: "text",
          size: 12,
          fields: [],
          isShowInList: false,
          isVisiblePublic: true,
          usersVisible: [],
        },
      ],
    },
    {
      id: 9,
      name: "consumo",
      description: "Consumo",
      datatype: "group",
      size: 12,
      fields: [
        {
          id: 5,
          isVisiblePublic: true,
          description: "Volume (L)",
          datatype: "number",
          size: 2.2,
          properties: {
            unit: "L",
            sizeDecimals: 3,
            min: 0,
          },
          name: "volume",
          fields: [],
          selected: false,
        },
        ...(hasPermissionViewFinancial
          ? [
            {
              id: 6,
              isVisiblePublic: true,
              description: "Preço (BRL)",
              datatype: "number",
              size: 2.2,
              properties: {
                unit: "R$",
                sizeDecimals: 2,
                min: 0,
              },
              name: "consumptionPrice",
              fields: [],
              selected: false,
            },
            {
              id: 8,
              isVisiblePublic: true,
              description: "Total",
              datatype: "textView",
              size: 6,
              properties: {
                unit: "R$",
                sizeDecimals: 2,
                min: 0,
              },
              name: "consumptionTotal",
              fields: [],
              selected: false,
            }]
          : []),
        {
          id: 1,
          description: "Estoque Inicial",
          datatype: "number",
          properties: {
            sizeDecimals: 3,
            min: 0,
            unit: "L",
          },
          isVisiblePublic: true,
          size: 2.2,
          name: "estoqueInicial",
          fields: [],
          selected: false,
        },
        {
          id: 4,
          isVisiblePublic: true,
          description: "Estoque Final",
          datatype: "number",
          size: 2.2,
          properties: {
            unit: "L",
            sizeDecimals: 3,
            min: 0,
          },
          name: "estoqueFinal",
          fields: [],
          selected: false,
        },
        {
          id: 2,
          isVisiblePublic: true,
          description: "Recebido",
          datatype: "number",
          size: 2.2,
          properties: {
            unit: "L",
            sizeDecimals: 2,
            min: 0,
          },
          name: "recebido",
          fields: [],
          selected: false,
        },
        {
          id: 3,
          isVisiblePublic: true,
          description: "Fornecido",
          datatype: "number",
          size: 2.2,
          properties: {
            unit: "L",
            sizeDecimals: 2,
            min: 0,
          },
          name: "fornecido",
          fields: [],
          selected: false,
        },
        {
          id: 7,
          isVisiblePublic: true,
          description: "Consumido",
          datatype: "textView",
          size: 2.2,
          properties: {
            unit: "L",
            sizeDecimals: 2,
            min: 0,
          },
          name: "consumido",
          fields: [],
          selected: false,
        },
      ],
      isVisiblePublic: true,
      usersVisible: [],
    },
  ]

  if (!!hasPermissionViewFinancial) {
    fields.push({
      id: 19,
      name: "others",
      description: "Outros",
      datatype: "group",
      subdatatype: "list",
      size: 12,
      fields: [
        {
          id: 20,
          name: "otherDescription",
          description: "Descrição",
          datatype: "text",
          size: 8,
          fields: [],
          isShowInList: false,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 21,
          name: "valueBRL",
          description: "Valor (BRL)",
          datatype: "number",
          properties: {
            sizeDecimals: 2,
            min: 0,
            unit: "R$",
          },
          size: 2,
          fields: [],
          isShowInList: false,
          isVisiblePublic: true,
          usersVisible: [],
        },
        {
          id: 21,
          name: "valueUSD",
          description: "Valor (USD)",
          datatype: "number",
          properties: {
            sizeDecimals: 2,
            min: 0,
            unit: "US$",
          },
          size: 2,
          fields: [],
          isShowInList: false,
          isVisiblePublic: true,
          usersVisible: [],
        }
      ],
      isVisiblePublic: true,
      usersVisible: [],
    })
  }

  return fields;
}
